version: '3.8'
services:
  app:
    image: node:lts-alpine
    container_name: react-app
    working_dir: /app
    volumes:
      - .:/app
      - /app/node_modules
    command: sh -c "npm install && npm run dev"
    ports:
      - "3000:3000"
  nginx:
    image: nginx:1.27.0-alpine
    container_name: nginx-server
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./dist:/usr/share/nginx/html
    ports:
      - "80:80"
    depends_on:
      - app
